import Foundation

/// A token set issued by Rauthy at the end of a successful sign-in or refresh.
///
/// Holds the access token (used for API authorization), the optional refresh
/// token (used to renew the access token without re-auth), and the optional
/// parsed ID token (used for user identity claims).
public struct Token: Sendable, Codable, Equatable {
    /// Session-scoped UUID, generated by the SDK at token-set creation time.
    ///
    /// This is NOT the JWT `jti` claim (access tokens typically have no jti).
    /// It exists so multiple tokens can be uniquely identified in storage and
    /// metadata operations.
    public let id: String

    /// Raw access token string. Send as `Authorization: Bearer <token>` to
    /// resource servers that accept Rauthy tokens.
    public let accessToken: String

    /// Optional refresh token. Present iff `offline_access` scope was granted.
    public let refreshToken: String?

    /// Optional parsed ID token. Present iff `openid` scope was granted.
    public let idToken: IDToken?

    /// Token type. v1.0 only accepts `.bearer`.
    public let tokenType: TokenType

    /// Granted scopes. May be a subset of the requested scopes if the user
    /// declined some at the consent screen.
    public let scope: [String]

    /// When this token set was issued. Used to compute `expiresAt`.
    public let issuedAt: Date

    /// Token lifetime in seconds from `issuedAt`.
    public let expiresIn: TimeInterval

    public init(
        id: String,
        accessToken: String,
        refreshToken: String?,
        idToken: IDToken?,
        tokenType: TokenType,
        scope: [String],
        issuedAt: Date,
        expiresIn: TimeInterval
    ) {
        self.id = id
        self.accessToken = accessToken
        self.refreshToken = refreshToken
        self.idToken = idToken
        self.tokenType = tokenType
        self.scope = scope
        self.issuedAt = issuedAt
        self.expiresIn = expiresIn
    }

    /// When this token expires. Computed from `issuedAt + expiresIn`.
    public var expiresAt: Date {
        issuedAt.addingTimeInterval(expiresIn)
    }

    /// Whether this token has expired (or will expire within `graceInterval` seconds).
    public func isExpired(graceInterval: TimeInterval = 0) -> Bool {
        Date().addingTimeInterval(graceInterval) >= expiresAt
    }

    /// Token type as returned by Rauthy's `/token` endpoint.
    ///
    /// v1.0 only handles `.bearer`. DPoP support is deferred to v1.1.
    public enum TokenType: String, Sendable, Codable, CaseIterable {
        case bearer = "Bearer"
    }

    /// Which sub-token within a token set is being referenced.
    public enum Kind: String, Sendable, CaseIterable {
        case access
        case refresh
        case id
    }

    /// Which token to revoke when calling `/oidc/revoke`.
    ///
    /// Rauthy follows RFC 7009 semantics: revoking the refresh token also
    /// invalidates the associated access token, but not vice versa.
    public enum RevokeType: Sendable, CaseIterable {
        /// Revoke only the access token. If a refresh token exists and
        /// `offline_access` was granted, it can mint a new access token.
        case access
        /// Revoke the refresh token, which implicitly invalidates the
        /// access token.
        case refresh
        /// Revoke both. Equivalent to `.refresh` in Rauthy's semantics.
        case all
    }
}
